### ISSUE TITLE
معرفة ما هو هذا ل | Descobrir para que é isso 

### ISSUE THREAD

**Issue by doponalopes** [viniceosm/GeradorFormulario#1]

**Comment by viniceosm** [comment]
A ideia é criar um template para teus formularios, assim você só escreve o id, name e tipo do campo, por exemplo e ele irá gerar o resto, como divs e outros elementos que você escolheu no template (que ainda será feito)

**Comment by doponalopes** [comment]
لقد وجدت ذلك رائعًا ، تهانينا ، تهانينا.

**Comment by viniceosm** [comment]
# Feel free to contribute!

- Fork the repository
- Create your feature branch (git checkout -b my-new-feature)
- Commit your changes (git commit -am 'Add some feature')
- Push to the branch (git push origin my-new-feature)
- Create a new Pull Request
